set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_ASM_COMPILER gcc)

set(CMAKE_C_FLAGS "-m32 -msse2")
set(CMAKE_CXX_FLAGS "-m32 -msse2")
set(CMAKE_ASM_FLAGS "-m32 -msse2")
